name: idle-timer
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  idletimer:
    name: idle-timer
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: build bazel-remote
        run: ./linux-build.sh
      - name: run with idle-timeout 1m
        run: for i in {1..20}; do sleep 1 ; curl --head --fail http://127.0.0.1:8080/cas/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ; done & ./bazel-remote --dir DATA --max_size 1 --idle_timeout 20s
